name: lint

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

jobs:
  gofmt:
    name: gofmt
    runs-on: ubuntu-latest
    container: golang:1.25
    steps:
      - uses: actions/checkout@v5.0.0
      - run: gofmt -s -l -d .
  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-go@v6.0.0
        with:
          go-version: '^1.25.0'
      - uses: dominikh/staticcheck-action@v1.4.0
        with:
          install-go: false
